services:
  mysql:
    build:
      context: ./encyclodb
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 4000:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - encyclodb:/var/lib/mysql
  dev:
    # path to ionic serve Dockerfile
    build:
      context: encyclofreedia
      dockerfile: Dockerfile.dev
    ports:
      - 80:8100
    command: ionic serve
  web:
    build: djangofreedia
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
  prod:
    # path to ionic build Dockerfile
    build:
      context: encyclofreedia
      dockerfile: Dockerfile.prod
    ports:
      - 443:443

volumes:
  encyclodb:
